# Generated by Django 4.1.4 on 2022-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumerno', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bpoint', models.IntegerField(default=0)),
                ('tcredit', models.IntegerField(default=0)),
                ('ucredit', models.IntegerField(default=0)),
                ('monthlycap', models.IntegerField(default=0)),
            ],
        ),
    ]
